### ISSUE TITLE
Fix the frontend formatting

### ISSUE THREAD

**Issue by anlhu** [adhocmaster/ScrumMate#40]
There are a few issues with the layout of the page:
Set the backlog to a fixed height
fix alignment issues with the backlog
fix alignment issues with the text boxes
fix alignment issues with the sanity check

**Comment by echen70** [comment]
Fix alignment issues with the sidebar

**Comment by anlhu** [comment]
Number of background colors/layers is too high

**Comment by echen70** [comment]
Change Sanity Check so that font size is consistent across the page

**Comment by anlhu** [comment]
Most of these seem fixed, I will separate the remaining ones into their own issues
